### ISSUE TITLE
duration handling is not so obvious

### ISSUE THREAD

**Issue by jdeantoni** [montoyadamien/cineditorml#6]
Two minor (but borring) things:

1. the during statement is expressed in seconds. So for a video which last for 14 minutes and 27 seconds, I actually need a calculator to write my scenario :-(
2. the during statement is required and it is boring if we want to put the whole video (or the reminder of the video)

(sorry for using your DSL :p )

**Comment by montoyadamien** [comment]
Hi,

For the first statement yes we need to calculate the seconds :/ 
For the second part, in fact we need to specify the video and musics duration because if we do not specify any duration, we ca not calculate the times to render the html timeline (since from gemoc we do not how much longer the asset is during)
